version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: trading
      POSTGRES_USER: tradinguser
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    env_file: .env
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: python3 trading_bot.py

volumes:
  pgdata: 